
**Lectura de un DATASET de MULTICLASIFICACION / INICIALIZACION DE LA RED CON NEURONAS**

In [27]:
import numpy as np
from RedNeu import cost, backprop , predict,initialize_parameters,update_parameters
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler,LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split


# En caso de solo tener un data set /Habria que mencionar que se podria estar usando kfold validation

##filepath="kartMULTI.csv"
##data =  pd.read_csv(filepath)
##X_train= data.drop("action", axis=1)
##VALUES= data["action"]
# X_train, X_test, y_train_split, y_test_split = train_test_split(X, VALUES, test_size=0.30, random_state=42)





# Lectura de datos en formato txt
file_path_train = "kartTrainMULTI.csv"
file_path_test = "kartTestMULTI.csv"


# Cargar los datos de entrenamiento
data_train = pd.read_csv(file_path_train)
data_test = pd.read_csv(file_path_test)

# Separar las características (X) y la variable objetivo (y)
X_train = data_train.drop("action", axis=1)
X_test = data_test.drop("action", axis=1)
X_train = X_train.drop("A", axis=1)
X_test = X_test.drop("A", axis=1)
print (X_train)

y_train_split = data_train["action"]
y_test_split = data_test["action"]


#SOLO SI ES MULTICLASE Y NO CLASIFICAION BINARIA 
# Convertir y_train_split a una matriz de etiquetas one-hot

encoder = OneHotEncoder(sparse=False)
Y_train_onehot = encoder.fit_transform(y_train_split.to_numpy().reshape(-1, 1))
Y_test_onehot = encoder.fit_transform(y_test_split.to_numpy().reshape(-1, 1))

# Añadir el sesgo a los conjuntos de entrenamiento y prueba
X_train_with_bias = np.hstack([np.ones((X_train.shape[0], 1)), X_train])
X_test_with_bias = np.hstack([np.ones((X_test.shape[0], 1)), X_test])



# El numero de neuronas de entrada siempre es igual a los parametros de entrada
# La salida igual, tenemos que la salida es la calidad de 0-10 así que 10 neuronas de salida
##Tantas neuronas de entrada como datos , y de salida si es binaria 2( o 1 o 0) y si es multi las que tenga y
layer_sizes = [X_train.shape[1], 10, Y_train_onehot.shape[1]]  # Ajusta el número de neuronas según sea necesario
theta_list = initialize_parameters(layer_sizes)



             B         C         D         E         F         G         H  \
0     6.520910  4.611073  6.489857  4.588929  15.98893  0.275700  3.105008   
1     6.520907  4.611071  6.489859  4.588931  15.98893  0.275717  3.105008   
2     6.520906  4.611070  6.489861  4.588932  15.98893  0.275722  3.105007   
3     6.520902  4.611067  6.489865  4.588934  15.98894  0.275743  3.105007   
4     6.520895  4.611062  6.489872  4.588939  15.98894  0.275746  3.105007   
...        ...       ...       ...       ...       ...       ...       ...   
2906  9.121757  5.322410  4.835673  4.017130  15.33107  0.279167 -9.927512   
2907  8.469483  5.462036  4.905059  3.773489  15.15157  0.279184 -8.394883   
2908  7.433750  5.428230  5.521473  3.776682  15.18696  0.279201 -7.033270   
2909  6.143655  5.248931  7.409981  4.148458  15.49571  0.279219 -5.558267   
2910  4.994212  4.936121 -1.000000  4.964962  16.07087  0.279219 -4.207523   

              I  
0      0.419318  
1      0.437750  
2      0.

c:\Users\danie\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
c:\Users\danie\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


**ENTRENAMIENTO DEL MODELO MLP**


In [28]:


# Ajustar hiperparámetros
lambdaValue = 0.025  # Experimenta con diferentes valores
alpha = 0.1  # Experimenta con diferentes valores
iterations = 1200  # Experimenta con diferentes valores

# Paso 3: Entrenamiento del perceptrón multicapa
for _ in range(iterations):
    J, grad = backprop(theta_list, X_train_with_bias, Y_train_onehot, lambdaValue)
    # Actualizar parámetros
    update_parameters(theta_list, grad, alpha)




**Prediccion de los datos y calculo de metricas de medida de rendimiento**


In [29]:
# Paso 4: Evaluación del perceptrón multicapa
predictions_test = predict(theta_list, X_test_with_bias)

# Obtener las etiquetas predichas (como índices de la clase con probabilidad máxima)
predicted_labels_test = np.argmax(predictions_test, axis=1)
# Obtener las etiquetas reales
true_labels_test = np.argmax(Y_test_onehot, axis=1)


accuracy_test = accuracy_score(true_labels_test, predicted_labels_test)
# Calcular la matriz de confusión
conf_matrix_test = confusion_matrix(true_labels_test, predicted_labels_test)

# Obtener True Positives (Verdaderos Positivos) y False Positives (Falsos Positivos) de la matriz de confusión
##ESTO SE HACE ASI POR QUE ES CLASIFICACION BINARIA ,EN ESTE EJEMPLO:  O PERSONA O CABALLO 
##SI ESTO FUESE MULTICLASE HABRIA QUE HACER UNA CLASE POSITIVA PARA CADA ETIQUETA
# Obtener True Positives (Verdaderos Positivos) y False Positives (Falsos Positivos) de la matriz de confusión
true_positives_class_1 = conf_matrix_test[1, 1]  # Posición [1, 1] para la clase positiva (1)
false_positives_class_1 = conf_matrix_test[0, 1]  # Posición [0, 1] para la clase negativa (0) clasificada como positiva (1)
# Obtener True Negatives (Verdaderos Negativos) y False Negatives (Falsos Negativos) de la matriz de confusión
true_negatives_class_0 = conf_matrix_test[0, 0]  # Posición [0, 0] para la clase negativa (0)
false_negatives_class_0 = conf_matrix_test[1, 0]  # Posición [1, 0] para la clase positiva (1) clasificada como negativa (0)



# Calcular Precision para la clase positiva (1)
precision_class_1 = true_positives_class_1 / (true_positives_class_1 + false_positives_class_1) if (true_positives_class_1 + false_positives_class_1) > 0 else 0
# Calcular Precision para la clase negativa (0)
precision_class_0 = true_negatives_class_0 / (true_negatives_class_0 + false_negatives_class_0) if (true_negatives_class_0 + false_negatives_class_0) > 0 else 0


# Definir nombres de las clases
class_names = ['ACCELERATE', 'LEFT_ACC','RIGHT_ACCELERATE']  # Reemplaza con los nombres específicos de tus clases
# Calcular el classification_report
report = classification_report(true_labels_test, predicted_labels_test,target_names=class_names)



c:\Users\danie\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\danie\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\danie\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**IMPRESION DE LOS RESULTADOS OBTENIDOS**

In [30]:
print(f'Costo de la red neuronal en entrenamiento: {cost(theta_list, X_train_with_bias, Y_train_onehot, lambdaValue):.2f}%')
print(f'Costo de la red neuronal en prueba: {cost(theta_list, X_test_with_bias, Y_test_onehot, lambdaValue):.2f}%')
print(f'Accuracy: {accuracy_test * 100:.2f}%')
# Imprimir la matriz de confusión
print("Matriz de Confusión en Test:")
print(conf_matrix_test)
# SE HACE ASI POR QUE SOLO HAY DOS CLASES ES BINARIA , SI FUESE MULTICLASE PONRIAMOS LAS QUE NOS INTERESEN
# Imprimir los  reportes obtenidos sobre las distintas clases 
print(report)
print("\nExplicaciones:")
print("Precision: Es la proporción de instancias clasificadas como positivas que son realmente positivas.")
print("Recall: Es la proporción de instancias positivas que fueron correctamente clasificadas como positivas.")
print("F1-score: Es la media armónica ponderada de precision y recall. Es útil cuando hay desbalance de clases.")
print("Support: Es el número real de ocurrencias de la clase en el conjunto de prueba.")
print("Accuracy: Es la proporción de instancias correctamente clasificadas en el conjunto de prueba.")
print("Macro avg: Es el promedio no ponderado de precision, recall y f1-score para todas las clases.")
print("Weighted avg: Es el promedio ponderado por el soporte (número de instancias) de precision, recall y f1-score.")

Costo de la red neuronal en entrenamiento: 1.16%
Costo de la red neuronal en prueba: 1.13%
Accuracy: 71.64%
Matriz de Confusión en Test:
[[732 279   0]
 [267 690   0]
 [ 13   4   0]]
                  precision    recall  f1-score   support

      ACCELERATE       0.72      0.72      0.72      1011
        LEFT_ACC       0.71      0.72      0.72       957
RIGHT_ACCELERATE       0.00      0.00      0.00        17

        accuracy                           0.72      1985
       macro avg       0.48      0.48      0.48      1985
    weighted avg       0.71      0.72      0.71      1985


Explicaciones:
Precision: Es la proporción de instancias clasificadas como positivas que son realmente positivas.
Recall: Es la proporción de instancias positivas que fueron correctamente clasificadas como positivas.
F1-score: Es la media armónica ponderada de precision y recall. Es útil cuando hay desbalance de clases.
Support: Es el número real de ocurrencias de la clase en el conjunto de prueba.
Accur

In [31]:
##PERCEPTRON DE SKLEARN
from sklearn.neural_network import MLPClassifier

##IMPORTANTE : SOBRE ESTE MODELO NO AÑADIMOS EL SESGO 
##EL MODELO INTEPRETA AUTOMATICAMENTE EL NUMERO DE CAPAS DE ENTRADA Y DE SALIDA 

mlp_sklearn = MLPClassifier(
    hidden_layer_sizes=(10,),  # Ajustar el número de neuronas en la capa oculta según sea necesario
    activation='logistic',        # Usar la función de activación
    max_iter=1000,             # Número máximo de iteraciones
    alpha=0.01,               # Término de regularización
    learning_rate_init=0.025,   # Tasa de aprendizaje inicial
    random_state=42
)
mlp_sklearn.fit(X_train, Y_train_onehot)  # Ajustar el modelo

# Hacer predicciones en el conjunto de prueba
predictions_sklearn = mlp_sklearn.predict(X_test)
# Obtener las etiquetas predichas (como índices de la clase con probabilidad máxima)
predicted_labels_test = np.argmax(predictions_sklearn, axis=1)
# Obtener las etiquetas reales
true_labels_test = np.argmax(Y_test_onehot, axis=1)

# Calcular métricas de evaluación del modelo de Scikit-Learn
accuracy_sklearn = accuracy_score(true_labels_test, predicted_labels_test)
conf_matrix_sklearn = confusion_matrix(true_labels_test, predicted_labels_test)
report_sklearn = classification_report(true_labels_test, predicted_labels_test, target_names=class_names)


print("\nResultados del Perceptrón Multicapa de Scikit-Learn:")
print(f'Accuracy: {accuracy_sklearn * 100:.2f}%')
print("Matriz de Confusión Test:")
print(conf_matrix_sklearn)
print(report_sklearn)
print(report)
print("\nExplicaciones:")
print("Precision: Es la proporción de instancias clasificadas como positivas que son realmente positivas.")
print("Recall: Es la proporción de instancias positivas que fueron correctamente clasificadas como positivas.")
print("F1-score: Es la media armónica ponderada de precision y recall. Es útil cuando hay desbalance de clases.")
print("Support: Es el número real de ocurrencias de la clase en el conjunto de prueba.")
print("Accuracy: Es la proporción de instancias correctamente clasificadas en el conjunto de prueba.")
print("Macro avg: Es el promedio no ponderado de precision, recall y f1-score para todas las clases.")
print("Weighted avg: Es el promedio ponderado por el soporte (número de instancias) de precision, recall y f1-score.")


Resultados del Perceptrón Multicapa de Scikit-Learn:
Accuracy: 73.30%
Matriz de Confusión Test:
[[753 258   0]
 [255 702   0]
 [ 13   4   0]]
                  precision    recall  f1-score   support

      ACCELERATE       0.74      0.74      0.74      1011
        LEFT_ACC       0.73      0.73      0.73       957
RIGHT_ACCELERATE       0.00      0.00      0.00        17

        accuracy                           0.73      1985
       macro avg       0.49      0.49      0.49      1985
    weighted avg       0.73      0.73      0.73      1985

                  precision    recall  f1-score   support

      ACCELERATE       0.72      0.72      0.72      1011
        LEFT_ACC       0.71      0.72      0.72       957
RIGHT_ACCELERATE       0.00      0.00      0.00        17

        accuracy                           0.72      1985
       macro avg       0.48      0.48      0.48      1985
    weighted avg       0.71      0.72      0.71      1985


Explicaciones:
Precision: Es la propor

c:\Users\danie\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\danie\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\danie\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Explicaciones sobre el uso de la red neuronal

Este código implementa una red neuronal para un problema de clasificación. A continuación, explicaré las funciones y parámetros:

## 1. Funciones de activación:

- `sigmoid(z)`: Devuelve el valor de la función sigmoide para la entrada 'z'.
- `sigmoid_gradient(z)`: Devuelve la derivada de la función sigmoide para la entrada 'z'.

## 2. Función de costo con regularización:

- `cost(theta_list, X, Y, lambda_)`: Calcula la función de costo para la red neuronal. Utiliza la entropía cruzada para la clasificación binaria y agrega términos de regularización para evitar el sobreajuste.

## 3. Función de predicción:

- `predict(theta_list, X)`: Realiza la propagación hacia adelante y devuelve las predicciones de la red neuronal.

## 4. Inicialización de parámetros:

- `initialize_parameters(layer_sizes)`: Inicializa los pesos de la red neuronal de manera aleatoria. 'layer_sizes' especifica el número de neuronas en cada capa.

## 5. Propagación hacia adelante:

- `forward_propagation(X, theta_list)`: Realiza la propagación hacia adelante y devuelve las activaciones y valores de 'z' para cada capa.

## 6. Actualización de parámetros:

- `update_parameters(theta_list, grads, learning_rate)`: Actualiza los pesos de la red neuronal utilizando el descenso de gradiente.

## 7. Propagación hacia atrás (Backpropagation):

- `backprop(theta_list, X, y, lambda_)`: Calcula el costo y los gradientes utilizando la propagación hacia atrás. Los gradientes se utilizan para la actualización de parámetros.

## Configuración de parámetros:

- `layer_sizes`: Se define como '[n_input, n_output]', donde 'n_input' es el número de características de entrada y 'n_output' es el número de neuronas en la capa de salida.
- `lambda_`: Parámetro de regularización. Controla la importancia de los términos de regularización en la función de costo.
- `learning_rate`: Tasa de aprendizaje para el descenso de gradiente.
- `iterations`: Número de iteraciones del descenso de gradiente.
**Tasa de Aprendizaje (Learning Rate):**

La tasa de aprendizaje es un parámetro que determina qué tan grandes son los pasos que la red neuronal toma durante el descenso de gradiente. Aquí hay algunas consideraciones al subir o bajar la tasa de aprendizaje:

- *Subir la Tasa de Aprendizaje:*
  - **Ventajas:** Puede conducir a convergencia más rápida durante el entrenamiento.
  - **Desventajas:** Si la tasa de aprendizaje es demasiado alta, el descenso de gradiente puede oscilar o divergir, lo que significa que los pesos pueden no converger a un mínimo global, y el entrenamiento puede volverse inestable.

- *Bajar la Tasa de Aprendizaje:*
  - **Ventajas:** Puede mejorar la estabilidad del entrenamiento y permitir una convergencia más suave.
  - **Desventajas:** Demorará más en converger, especialmente en conjuntos de datos grandes. Si la tasa de aprendizaje es demasiado baja, el modelo puede tardar demasiado en aprender y puede quedar atrapado en mínimos locales.

**Recomendaciones:**
- Comienza con una tasa de aprendizaje moderada y ajústala según sea necesario.
- Utiliza técnicas como la disminución adaptativa del learning rate para ajustar dinámicamente la tasa de aprendizaje durante el entrenamiento.

---

**Parámetro de Regularización (Alfa o Lambda):**

El parámetro de regularización controla la magnitud de la penalización aplicada a los pesos de la red para prevenir el sobreajuste. Aquí hay algunas consideraciones al subir o bajar el parámetro de regularización:

- *Subir el Parámetro de Regularización:*
  - **Ventajas:** Puede ayudar a prevenir el sobreajuste al penalizar pesos grandes.
  - **Desventajas:** Si es demasiado alto, puede llevar a una supresión excesiva de los pesos, haciendo que el modelo sea demasiado simple y no capte patrones complejos en los datos.

- *Bajar el Parámetro de Regularización:*
  - **Ventajas:** Puede permitir que el modelo capture patrones más complejos en los datos.
  - **Desventajas:** Aumenta el riesgo de sobreajuste, especialmente en conjuntos de datos pequeños o cuando la complejidad del modelo es alta.

**Recomendaciones:**
- Utilizo validación cruzada para encontrar el valor óptimo del parámetro de regularización.
- Experimento con valores en una escala logarítmica (0.1, 0.01, 0.001, etc.) para encontrar el equilibrio adecuado entre regularización y capacidad del modelo.

## Uso de la codificación one-hot para problemas multiclase:

- Cuando se enfrenta a un problema de clasificación multiclase, la codificación one-hot se aplica a las etiquetas de clase. Esta codificación convierte las etiquetas de clase en vectores binarios, donde cada vector representa una clase única y la posición del 1 indica la clase.
- La función de costo y las funciones de actualización de parámetros han sido diseñadas para manejar problemas de clasificación binaria y multiclase mediante el uso de one-hot encoding.

## Análisis:

- La red neuronal es adecuada tanto para problemas de clasificación binaria como multiclase.
- La codificación one-hot aborda eficazmente el problema multiclase y permite que la red clasifique instancias en más de dos clases.
- Es importante ajustar la tasa de aprendizaje y el término de regularización para obtener un rendimiento óptimo en problemas multiclase.
- Las redes neuronales, especialmente las más profundas, tienden a necesitar grandes cantidades de datos para entrenarse de manera efectiva. Si tienes un conjunto de datos relativamente pequeño, podrías enfrentar problemas de sobreajuste.
- La red neuronal también se puede mejorar mediante el uso de validación cruzada.

## Esta configuración de la red resuelve problemas de tres tipos:

1. **Problema Multiclase String**: Ejemplo de clasificación de acciones ("Action", "Accelerate", etc.).
2. **Problema Multiclase Numérico**: Ejemplo de clasificación de calidad del vino (0-9).
3. **Problemas de Clasificación Binaria**: Ejemplo de clasificación de si el vino es bueno o no.
4.  **Problema de Clasificacion de Imagenes** Otro tipo de problema de  clasificacion , en archivos . mat

### Modelos Recomendados:
# 1. Clasificación Binaria: Redes Neuronales con Capas Ocultas
## Motivos:
- **Aprendizaje de Representaciones Complejas:** Las redes neuronales permiten aprender representaciones no lineales y complejas de los datos. En problemas de clasificación binaria, donde las relaciones entre las características y la salida pueden ser no lineales, las capas ocultas de la red neuronal pueden capturar patrones más sofisticados.
- **Extracción de Características Abstractas:** Las capas ocultas posibilitan la extracción de características más abstractas y complejas. Esto es esencial cuando las relaciones subyacentes en los datos no son evidentes y requieren representaciones más profundas para su comprensión.
- **Manejo de Patrones No Lineales:** Las redes neuronales son especialmente aptas para manejar patrones no lineales en los datos. En problemas de clasificación binaria, donde las decisiones de clasificación pueden estar basadas en relaciones complejas, las redes neuronales pueden superar las limitaciones de modelos más simples como la regresión logística.

# 2. Clasificación de Imagenes: Redes Neuronales Convolucionales (CNN)
## Motivos:
- **Efectividad en Clasificación de Imágenes:** Las CNN son altamente efectivas en la clasificación de datos de imágenes. Están diseñadas para aprender jerarquías de características, desde características simples hasta más complejas, lo que es esencial para interpretar datos visuales.
- **Captura de Patrones Espaciales y de Textura:** Las CNN son capaces de capturar patrones espaciales y de textura en datos bidimensionales como imágenes. La arquitectura convolucional permite la extracción eficiente de características locales, lo que es crucial en problemas de clasificación de texto.
- **Reducción de Parámetros con Compartición de Pesos:** La arquitectura convolucional reduce el número de parámetros al compartir pesos. Esto es beneficioso en conjuntos de datos grandes como imágenes, donde se pueden aprender patrones locales que son útiles en diferentes partes de la imagen.

# 3. Clasificación Multiclase : Regresión Logística o Redes Neuronales FeedFoward
## Motivos:
- **Eficiencia de la Regresión Logística:** La regresión logística es simple y efectiva para problemas de clasificación multiclase. Cuando la relación entre las características y la salida es relativamente lineal, la regresión logística puede ser una opción eficiente.
- **Adaptabilidad de las Redes Neuronales:** Las redes neuronales pueden adaptarse mejor a patrones no lineales y relaciones complejas en comparación con la regresión logística. Si el problema presenta una complejidad significativa, las redes neuronales pueden capturar mejor estas relaciones.
- **Elección Dependiendo del Tamaño del Conjunto de Datos:** La elección entre regresión logística y redes neuronales puede depender del tamaño del conjunto de datos. En conjuntos de datos pequeños, la regresión logística puede ser menos propensa al sobreajuste.

# Comparaciones y Consideraciones Generales:
- **Tamaño del Conjunto de Datos:**
  - *Conjuntos Pequeños:* Modelos más simples como la regresión logística pueden ser preferibles para evitar sobreajuste en conjuntos de datos pequeños.
  - *Conjuntos Grandes:* Modelos más complejos como las redes neuronales pueden aprovechar mejor conjuntos de datos grandes para aprender patrones más complejos.
- **Complejidad del Problema:**
  - *No Linealidades y Complejidades:* Problemas con patrones no lineales y relaciones complejas entre las características pueden beneficiarse de modelos más complejos como las redes neuronales.
- **Interpretabilidad:**
  - *Claridad de Coeficientes:* La regresión logística ofrece una interpretación clara de los coeficientes para cada característica, lo que puede ser crucial en aplicaciones donde la interpretabilidad es fundamental.
  - *Complejidad de las Redes Neuronales:* Las redes neuronales pueden ser menos interpretables debido a su complejidad, y la interpretación de cómo las características contribuyen a las decisiones puede ser más desafiante.
- **Tiempo de Entrenamiento:**
  - *Modelos Complejos:* Modelos más complejos, como las redes neuronales profundas, pueden requerir más tiempo de entrenamiento, especialmente en conjuntos de datos grandes. Esto debe considerarse en aplicaciones donde el tiempo de entrenamiento es un factor crítico.
- **Validación Cruzada:**
  - *Evaluación del Rendimiento:* La validación cruzada es crucial para evaluar el rendimiento del modelo en diferentes conjuntos de datos y evitar el sobreajuste. Es especialmente importante en problemas con conjuntos de datos limitados.

